<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class IdentityVerificationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('identity_verifications')->insert([
            [
                'userID' => 1,
                'full_name' => 'Nguyễn Văn A',
                'identity_number' => '012345678901',
                'birth_date' => '2005-06-01',
                'nationality' => 'Vietnam',
                'gender' => 'male',
                'hometown' => 'Hà Nội',
                'residence' => 'TP Hồ Chí Minh',
                'identity_type' => 'cccd',
                'identity_card_date' => '2015-01-01',
                'identity_card_place' => 'Cục Cảnh sát QLHC về TTXH',
                'identity_card_image' => 'uploads/idcard.jpg',
                'identity_card_holding_image' => 'uploads/holding.jpg',
                'status' => 'pending',
                'rejection_reason' => NULL,
                'verified_by' => NULL,
                'verified_at' => NULL,
                'created_at' => '2025-06-12 05:38:49',
                'updated_at' => '2025-06-12 05:38:49',
            ],
            [
                'userID' => 2,
                'full_name' => 'Nguyễn Thị C',
                'identity_number' => '111111111111',
                'birth_date' => '1995-03-15',
                'nationality' => 'Vietnam',
                'gender' => 'female',
                'hometown' => 'Đà Nẵng',
                'residence' => 'Huế',
                'identity_type' => 'cccd',
                'identity_card_date' => '2015-01-20',
                'identity_card_place' => 'CA Đà Nẵng',
                'identity_card_image' => 'uploads/1.jpg',
                'identity_card_holding_image' => 'uploads/1_holding.jpg',
                'status' => 'pending',
                'rejection_reason' => NULL,
                'verified_by' => NULL,
                'verified_at' => NULL,
                'created_at' => '2025-06-25 05:55:08',
                'updated_at' => '2025-06-25 05:55:08',
            ],
            [
                'userID' => NULL,
                'full_name' => 'Trần Văn D',
                'identity_number' => '222222222222',
                'birth_date' => '1998-07-21',
                'nationality' => 'Vietnam',
                'gender' => 'male',
                'hometown' => 'TP HCM',
                'residence' => 'Cần Thơ',
                'identity_type' => 'cccd',
                'identity_card_date' => '2016-05-10',
                'identity_card_place' => 'CA TP HCM',
                'identity_card_image' => 'uploads/2.jpg',
                'identity_card_holding_image' => 'uploads/2_holding.jpg',
                'status' => 'pending',
                'rejection_reason' => NULL,
                'verified_by' => NULL,
                'verified_at' => NULL,
                'created_at' => '2025-06-25 05:55:08',
                'updated_at' => '2025-06-25 05:55:08',
            ],
            [
                'userID' => NULL,
                'full_name' => 'Lê Thị E',
                'identity_number' => '333333333333',
                'birth_date' => '2000-12-02',
                'nationality' => 'Vietnam',
                'gender' => 'female',
                'hometown' => 'Hải Phòng',
                'residence' => 'Hà Nội',
                'identity_type' => 'cmnd',
                'identity_card_date' => '2013-03-18',
                'identity_card_place' => 'CA Hải Phòng',
                'identity_card_image' => 'uploads/3.jpg',
                'identity_card_holding_image' => 'uploads/3_holding.jpg',
                'status' => 'pending',
                'rejection_reason' => NULL,
                'verified_by' => NULL,
                'verified_at' => NULL,
                'created_at' => '2025-06-25 05:55:08',
                'updated_at' => '2025-06-25 05:55:08',
            ],
            [
                'userID' => NULL,
                'full_name' => 'Phạm Văn F',
                'identity_number' => '444444444444',
                'birth_date' => '1993-09-09',
                'nationality' => 'Vietnam',
                'gender' => 'male',
                'hometown' => 'Quảng Ninh',
                'residence' => 'TP HCM',
                'identity_type' => 'cccd',
                'identity_card_date' => '2011-11-11',
                'identity_card_place' => 'CA Quảng Ninh',
                'identity_card_image' => 'uploads/4.jpg',
                'identity_card_holding_image' => 'uploads/4_holding.jpg',
                'status' => 'pending',
                'rejection_reason' => NULL,
                'verified_by' => NULL,
                'verified_at' => NULL,
                'created_at' => '2025-06-25 05:55:08',
                'updated_at' => '2025-06-25 05:55:08',
            ],
            [
                'userID' => NULL,
                'full_name' => 'Hoàng Thị G',
                'identity_number' => '555555555555',
                'birth_date' => '1997-06-06',
                'nationality' => 'Vietnam',
                'gender' => 'female',
                'hometown' => 'Nghệ An',
                'residence' => 'Hà Tĩnh',
                'identity_type' => 'cccd',
                'identity_card_date' => '2014-07-07',
                'identity_card_place' => 'CA Nghệ An',
                'identity_card_image' => 'uploads/5.jpg',
                'identity_card_holding_image' => 'uploads/5_holding.jpg',
                'status' => 'pending',
                'rejection_reason' => NULL,
                'verified_by' => NULL,
                'verified_at' => NULL,
                'created_at' => '2025-06-25 05:55:08',
                'updated_at' => '2025-06-25 05:55:08',
            ],
            [
                'userID' => NULL,
                'full_name' => 'Đỗ Văn H',
                'identity_number' => '666666666666',
                'birth_date' => '1989-08-08',
                'nationality' => 'Vietnam',
                'gender' => 'male',
                'hometown' => 'Hà Nam',
                'residence' => 'Hà Nội',
                'identity_type' => 'cmnd',
                'identity_card_date' => '2010-09-09',
                'identity_card_place' => 'CA Hà Nam',
                'identity_card_image' => 'uploads/6.jpg',
                'identity_card_holding_image' => 'uploads/6_holding.jpg',
                'status' => 'pending',
                'rejection_reason' => NULL,
                'verified_by' => NULL,
                'verified_at' => NULL,
                'created_at' => '2025-06-25 05:55:08',
                'updated_at' => '2025-06-25 05:55:08',
            ],
            [
                'userID' => NULL,
                'full_name' => 'Vũ Thị I',
                'identity_number' => '777777777777',
                'birth_date' => '2001-01-01',
                'nationality' => 'Vietnam',
                'gender' => 'female',
                'hometown' => 'Bình Định',
                'residence' => 'TP HCM',
                'identity_type' => 'cccd',
                'identity_card_date' => '2019-02-02',
                'identity_card_place' => 'CA Bình Định',
                'identity_card_image' => 'uploads/7.jpg',
                'identity_card_holding_image' => 'uploads/7_holding.jpg',
                'status' => 'pending',
                'rejection_reason' => NULL,
                'verified_by' => NULL,
                'verified_at' => NULL,
                'created_at' => '2025-06-25 05:55:08',
                'updated_at' => '2025-06-25 05:55:08',
            ],
            [
                'userID' => NULL,
                'full_name' => 'Ngô Văn K',
                'identity_number' => '888888888888',
                'birth_date' => '1990-10-10',
                'nationality' => 'Vietnam',
                'gender' => 'male',
                'hometown' => 'Thanh Hóa',
                'residence' => 'Ninh Bình',
                'identity_type' => 'cmnd',
                'identity_card_date' => '2008-08-08',
                'identity_card_place' => 'CA Thanh Hóa',
                'identity_card_image' => 'uploads/8.jpg',
                'identity_card_holding_image' => 'uploads/8_holding.jpg',
                'status' => 'pending',
                'rejection_reason' => NULL,
                'verified_by' => NULL,
                'verified_at' => NULL,
                'created_at' => '2025-06-25 05:55:08',
                'updated_at' => '2025-06-25 05:55:08',
            ],
            [
                'userID' => NULL,
                'full_name' => 'Bùi Thị L',
                'identity_number' => '999999999999',
                'birth_date' => '1996-04-04',
                'nationality' => 'Vietnam',
                'gender' => 'female',
                'hometown' => 'Vĩnh Long',
                'residence' => 'Cần Thơ',
                'identity_type' => 'cccd',
                'identity_card_date' => '2015-05-05',
                'identity_card_place' => 'CA Vĩnh Long',
                'identity_card_image' => 'uploads/9.jpg',
                'identity_card_holding_image' => 'uploads/9_holding.jpg',
                'status' => 'pending',
                'rejection_reason' => NULL,
                'verified_by' => NULL,
                'verified_at' => NULL,
                'created_at' => '2025-06-25 05:55:08',
                'updated_at' => '2025-06-25 05:55:08',
            ],
            [
                'userID' => NULL,
                'full_name' => 'Đinh Văn M',
                'identity_number' => '101010101010',
                'birth_date' => '1994-11-11',
                'nationality' => 'Vietnam',
                'gender' => 'male',
                'hometown' => 'Bắc Giang',
                'residence' => 'Hà Nội',
                'identity_type' => 'cmnd',
                'identity_card_date' => '2012-12-12',
                'identity_card_place' => 'CA Bắc Giang',
                'identity_card_image' => 'uploads/10.jpg',
                'identity_card_holding_image' => 'uploads/10_holding.jpg',
                'status' => 'pending',
                'rejection_reason' => NULL,
                'verified_by' => NULL,
                'verified_at' => NULL,
                'created_at' => '2025-06-25 05:55:08',
                'updated_at' => '2025-06-25 05:55:08',
            ],
        ]);
    }
} 